name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-helm-repo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Helm 매니페스트 레포지토리 체크아웃
      - name: Checkout Helm repository
        uses: actions/checkout@v4
        with:
          repository: yj7673/app-helm # 변경 필요
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      # 2. CI 커밋 메시지 추출 및 이미지 주소 수정
      - name: Update app image in values.yaml
        id: update_tag
        run: |
          # CI를 발생시킨 원본 커밋 메시지 전체 추출
          ORIGINAL_MSG="${{ github.event.workflow_run.head_commit.message }}"
          
          # 태그용 (특수문자 제거)
          SAFE_TAG=$(echo "$ORIGINAL_MSG" | tr -dc '[:alnum:]' | cut -c1-50)
          if [ -z "$SAFE_TAG" ]; then SAFE_TAG="latest"; fi
          
          DOCKER_USER="${{ secrets.DOCKER_USERNAME }}"
          DOCKER_REPO="${{ secrets.DOCKER_REPO }}"
          NEW_IMAGE="${DOCKER_USER}/${DOCKER_REPO}:${SAFE_TAG}"
          TARGET_FILE="charts/myapp/values.yaml"
          
          # 파일 수정
          sed -i "/^app:/!b;n;s|[[:space:]]*image:.*|  image: ${NEW_IMAGE}|" "$TARGET_FILE"
          
          # 슬랙 알림에서 사용하기 위해 환경 변수에 저장
          echo "SAFE_TAG=$SAFE_TAG" >> $GITHUB_ENV
          echo "ORIGINAL_MSG=$ORIGINAL_MSG" >> $GITHUB_ENV

      # 3. 변경사항 커밋 및 푸시
      - name: Commit and push changes
        run: |
          git config --global user.name "yj7673" # 변경 필요
          git config --global user.email "trost.creator@gmail.com" #변경 필요
          
          git add charts/myapp/values.yaml
          
          if git diff --staged --quiet; then
            echo "CHANGED=false" >> $GITHUB_ENV
            echo "No changes to commit."
          else
            git commit -m "chore: update image to $SAFE_TAG"
            git push origin main
            echo "CHANGED=true" >> $GITHUB_ENV
          fi